### ISSUE TITLE
Cannot run on Linux

### ISSUE THREAD

**Issue by haiyaku365** [haiyaku365/StimmingSignalGenerator#1]
NAudio Lib is not currently cross-platform.
[UNIX port?](https://github.com/naudio/NAudio/issues/184)

**Comment by haiyaku365** [comment]
Able to get wave out with OpenAL from OpenTK 4.0.0-pre9.1
b2247aad518ab119346afb28e5cdb9c4869f8363

**Comment by dev-bre** [comment]
Is there any plan on adding audio capture to work on Linux as well?

**Comment by haiyaku365** [comment]
I'm not plan on adding audio input.
