### ISSUE TITLE
Do you plan on supporting audio input from microphone?

### ISSUE THREAD

**Issue by dev-bre** [haiyaku365/StimmingSignalGenerator#4]
Hi,
I can see you built a wrapper for NAudio for audio output using OpenAl via OpenTk.
Any chance you could provide an NAudio wrapper for audio capture using OpenTk as well?

**Comment by haiyaku365** [comment]
I'm not plan on adding audio input.

If you want to dig deeper on OpenAL side I suggest you take a look in 
OpenAL_Programmers_Guide.pdf
https://github.com/opentk/opentk/tree/master/OpenALTest

On NAudio side I have no idea how NAudio work with audio input.
